# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_all

ortools_datas, ortools_binaries, ortools_hiddenimports = collect_all('ortools')

hidden_modules = [
    'perfect_scheduler',
    'kempe_scheduler',
    'tabu_repair',
    'chain_scheduler',
    'placement_engine',
    'dialogs',
    'dialogs.preflight_dialog',
    'dialogs.advanced_wizard',
    'dialogs.advisor_dialog',
    'dialogs.assignment_list_dialog',
    'dialogs.auto_schedule_dialog',
    'dialogs.base_dialog',
    'dialogs.bell_times_dialog',
    'dialogs.classes_dialog',
    'dialogs.color_picker_dialog',
    'dialogs.compare_dialog',
    'dialogs.constraints_dialog',
    'dialogs.days_dialog',
    'dialogs.edit_forms',
    'dialogs.electives_dialog',
    'dialogs.export_dialog',
    'dialogs.extracted_dialog',
    'dialogs.faq_dialog',
    'dialogs.groups_dialog',
    'dialogs.master_data_dialog',
    'dialogs.notifications_dialog',
    'dialogs.print_preview',
    'dialogs.print_wizard',
    'dialogs.profile_dialog',
    'dialogs.relations_dialog',
    'dialogs.report_selection_dialog',
    'dialogs.room_assign_dialog',
    'dialogs.rooms_dialog',
    'dialogs.save_location_dialog',
    'dialogs.school_info',
    'dialogs.startup_wizard',
    'dialogs.statistics_dialog',
    'dialogs.subjects_dialog',
    'dialogs.teachers_dialog',
    'dialogs.test_timetable_dialog',
    'dialogs.timeoff_dialog',
    'dialogs.verify_timetable_dialog',
    'dialogs.wizard_dialog',
    'advisor',
    'api_client',
    'auto_scheduler',
    'cloud_sync',
    'constraint_sync',
    'database',
    'exporters',
    'home_dashboard',
    'lesson_hours',
    'login_dialog',
    'main_window',
    'ribbon_widget',
    'save_dialog',
    'splash_screen',
    'state_manager',
    'timetable_grid',
    'updater',
    'version',
    'version_store',
    'core.timetable_data',
] + ortools_hiddenimports

datas = [
    ('resources', 'resources'),
    ('data', 'data'),
    ('dialogs', 'dialogs'),
    ('bgz_database.json', '.'),
    ('app_icon.png', '.'),
    ('app_icon.ico', '.'),
    ('11.png', '.'),
    ('ChatGPT Image 16 Ağu 2026 10_31_17.png', '.'),
    ('C:/Users/gokay/Desktop/aSc/IMG_4327 (1).PNG', '.'),
    ('C:/Users/gokay/Desktop/aSc/ChatGPT Image 5 Tem 2026 01_04_30.png', '.')
] + ortools_datas

binaries = ortools_binaries

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hidden_modules,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='BGZ_Ders_Planlama_Final_v60',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app_icon.ico'],
)
